name: vscpd
version: 14.0.0
summary: VSCP daemon
description: This is a VSCP daemon/sever that among other things act as a hub
    for VSCP events from/to different sources.
    The VSCP protocol/framework is one of the first IoT/m2m protocols/frameworks
    that has been developed. It was available already in 2000. VSCP defines a
    set of events that make it possible for system with different properties to 
    talk to each other. VSCP & Friends is software and tools that can be used
    with VSCP based systems.
confinement: strict
grade: stable

apps:
  vscpd:
    command: launcher.sh
    daemon: simple
    restart-condition: always
    plugs: [home, network, network-bind]

  pub:
    command: usr/bin/vscpd_pub
    plugs: [home, network]

  rr:
    command: usr/bin/vscpd_rr
    plugs: [home, network]

  sub:
    command: usr/bin/vscpd_sub
    plugs: [home, network]

  passwd:
    command: usr/bin/vscpd_passwd
    plugs: [home]


parts:
  script:
    plugin: dump
    source: snap/local/
    prime:
      - default_config.conf
      - launcher.sh
  config:
    plugin: dump
    source: .
    prime:
      - vscpd.xml


  vscpd:
    after:
      - lws
    plugin: make
    make-parameters: ["prefix=/usr", "WITH_WEBSOCKETS=yes", "WITH_ADNS=yes", "CFLAGS=-Wall -ggdb -O2 -I$SNAPCRAFT_STAGE -D_GNU_SOURCE"]
    source: https://github.com/eclipse/vscpd
    source-type: git

    build-packages:
      - libssl-dev
      - xsltproc
      - docbook-xsl
      - gcc
      - g++
    stage-packages:
      - libssl1.0.0
      - ca-certificates
    prime:
      - usr/sbin/vscpd
      - usr/bin/vscpd_pub
      - usr/bin/vscpd_rr
      - usr/bin/vscpd_sub
      - usr/bin/vscpd_passwd
      - usr/lib/libvscpd.so*
      - lib/*-linux-gnu/libcrypto.so*
      - lib/*-linux-gnu/libssl.so*
      - usr/include/vscpd.h
      - usr/include/vscpd_broker.h
      - usr/include/vscpd_plugin.h

  lws:
    plugin: cmake
    configflags: ["-DLWS_IPV6=ON", "-DLWS_WITHOUT_CLIENT=ON", "-DLWS_WITHOUT_EXTENSIONS=ON", "-DLWS_WITH_ZIP_FOPS=OFF", "-DLWS_WITH_ZLIB=OFF", "-DLWS_WITH_SHARED=OFF"]
    source: https://github.com/warmcat/libwebsockets/archive/v2.4.2.tar.gz
    source-type: tar
    stage:
      - include/libwebsockets.h
      - include/lws_config.h
      - lib/libwebsockets.a
    prime: [-*]
